#服务器配置
server:
 port: 80
 session-timeout: 30
 tomcat.max-threads: 0
 tomcat.uri-encoding: UTF-8
 
 #spring相关配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #content-type: text/html
    cache: false
 #配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    
    #配置jpa（hibernate）相关信息
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 